### ISSUE TITLE
Mocha merge shows incorrect Duration and Suites - post merging multiple json files

### ISSUE THREAD

**Issue by chan90git** [Antontelesh/mochawesome-merge#71] opened 2021-08-25 05:05 UTC
We have a scenario, where I merge multiple mochawesome report json files, below are the env depedencies :
"devDependencies": {
 ......
    "mocha": "^7.0.1",
    "mocha-parallel-tests": "^2.3.0",
    "mochawesome": "^6.1.1",
    "mochawesome-screenshots": "^1.5.9",
  },
  "dependencies": {
............
    "mocha-reporter": "^0.1.1",
    "mochawesome-report-generator": "5.1.0",
  }
---------------------------------------------------------------
json files content : -
report_1.json : 
{
  "stats": {
    "suites": 90,
    "tests": 340,
    "passes": 322,
    "pending": 0,
    "failures": 18,
    "start": "2021-08-24T12:10:22.613Z",
    "end": "2021-08-24T12:59:48.230Z",
    "duration": 2965617,
    "testsRegistered": 340,
    "passPercent": 94.70588235294117,
    "pendingPercent": 0,
    "other": 0,
    "hasOther": false,
    "skipped": 0,
    "hasSkipped": false
  }, ......
------------------------------------------------------------------------
report_2.json : 
{
  "stats": {
    "suites": 160,
    "tests": 271,
    "passes": 249,
    "pending": 0,
    "failures": 22,
    "start": "2021-08-24T12:10:26.036Z",
    "end": "2021-08-24T13:31:17.299Z",
    "duration": 4851263,
    "testsRegistered": 355,
    "passPercent": 70.14084507042253,
    "pendingPercent": 0,
    "other": 35,
    "hasOther": true,
    "skipped": 84,
    "hasSkipped": true
  }

Issue observed is  : -
report_1.json -> shows about 49 minutes as duration
report_2.json -> shown about 1.5 hours as duration
and one more .json file -> which would be less than 2 seconds or so

post merging the above json files, Im seeing the below data wrong
1) duration as "5:10h" in the html report, but actual should be 1.5 hr + 49 m =~ 2.5 hrs
2) suites as 3 in the html report, but actual should be > 250
![image](https://user-images.githubusercontent.com/27766769/130729254-b4a4253d-970c-4a33-b8d4-eb28280894dc.png)

But all other details like Tests, Passed, Failed etc are set correct.

**Comment by rcsekar90** [comment] 2021-09-28 03:47
Any update on this ? it would be helpful if we could get it resolved soon.

**Comment by Antontelesh** [comment] 2021-09-28 10:04
@rcsekar90 I’m open to your pull requests guys

**Comment by Antontelesh** [comment] 2021-12-02 19:05
Closing as a duplicate of #61

**Closed** 2021-12-02 19:05 UTC
