### ISSUE TITLE
Problem with mochawesome merge - value passPercent is null

### ISSUE THREAD

**Issue by monikajastrzebska** [Antontelesh/mochawesome-merge#13] opened 2019-06-05 09:32 UTC
Mochawesome-merge generate json file:
`{
  "stats": {
    "suites": 0,
    "tests": 0,
    "passes": 0,
    "pending": 0,
    "failures": 0,
    "start": "2019-06-05T09:04:22.006Z",
    "end": "2019-06-05T09:04:22.006Z",
    "duration": 0,
    "testsRegistered": 0,
    "passPercent": null,
    "pendingPercent": null,
    "other": 0,
    "hasOther": false,
    "skipped": 0,
    "hasSkipped": false,
    "passPercentClass": "warning",
    "pendingPercentClass": "danger"
  },
  "suites": {
    "uuid": "918d149e-d6c8-4996-b325-fbd136947b03",
    "tests": [],
    "suites": [],
    "duration": 0,
    "root": true,
    "rootEmpty": true,
    "title": "",
    "fullFile": "",
    "file": "",
    "beforeHooks": [],
    "afterHooks": [],
    "passes": [],
    "failures": [],
    "pending": [],
    "skipped": [],
    "_timeout": 2000
  },
  "copyrightYear": 2019
}`

when I try to create HTML report file I have errors:
`Some files could not be processed:
mochawesome.json
  Invalid value null supplied to /stats/passPercent: Number
  Invalid value null supplied to /stats/pendingPercent: Number
  Invalid value "warning" supplied to /stats/passPercentClass: Nil
  Invalid value "danger" supplied to /stats/pendingPercentClass: Nil
  Invalid value undefined supplied to /results: Array<Suite>
  Invalid value {
  "uuid": "918d149e-d6c8-4996-b325-fbd136947b03",
  "tests": [],
  "suites": [],
  "duration": 0,
  "root": true,
  "rootEmpty": true,
  "title": "",
  "fullFile": "",
  "file": "",
  "beforeHooks": [],
  "afterHooks": [],
  "passes": [],
  "failures": [],
  "pending": [],
  "skipped": [],
  "_timeout": 2000
} supplied to /suites: Nil
  Invalid value 2019 supplied to /copyrightYear: Nil`

My mochawaesome verssion: 
"mochawesome": 4.0.
 "mochawesome-merge": 1.0.7
 "mochawesome-report-generator": 4.0.0

**Comment by deane187** [comment] 2019-06-05 13:11
I'm experiencing the same issue.
```
"mocha": "5.2.0",
"mocha-junit-reporter": "^1.21.0",
"mocha-multi-reporters": "^1.1.7",
"mocha-slack-reporter": "0.0.8",
"mochawesome": "^3.1.2",
"mochawesome-merge": "^1.0.7",
"mochawesome-report-generator": "^3.1.5"
```

I have 3 Json files in cypress/reports/mocha That are generated after a test run with 3 spec files.
example of one of the json files:
```{
  "stats": {
    "suites": 1,
    "tests": 1,
    "passes": 1,
    "pending": 0,
    "failures": 0,
    "start": "2019-06-05T12:50:41.097Z",
    "end": "2019-06-05T12:50:49.744Z",
    "duration": 8647,
    "testsRegistered": 1,
    "passPercent": 100,
    "pendingPercent": 0,
    "other": 0,
    "hasOther": false,
    "skipped": 0,
    "hasSkipped": false,
    "passPercentClass": "success",
    "pendingPercentClass": "danger"
  },
  "suites": {
    "uuid": "c2e88d15-c1a5-4578-8836-7b3c3169bcbc",
    "title": "",
    "fullFile": "",
    "file": "",
    "beforeHooks": [],
    "afterHooks": [],
    "tests": [],
    "suites": [
      {
        "uuid": "89dd1f02-21b3-47c4-a775-3e0ad9dda44b",
        "title": "Mentions Experience Test",
        "fullFile": "",
        "file": "",
        "beforeHooks": [],
        "afterHooks": [],
        "tests": [
          {
            "title": "Login to Blue Robot Admin Frontend.",
            "fullTitle": "Mentions Experience Test Login to Blue Robot Admin Frontend.",
            "duration": 6757,
            "state": "passed",
            "speed": "slow",
            "pass": true,
            "fail": false,
            "pending": false,
            "code": "cy.visit(\"https://staging.bluerobot.com/login\");\ncy.wait(5000);\ncy.percySnapshot(\"home-screen\");",
            "err": {},
            "isRoot": false,
            "uuid": "74550503-59aa-4d43-b969-95c9d9a19785",
            "isHook": false,
            "skipped": false
          }
        ],
        "suites": [],
        "passes": [
          "74550503-59aa-4d43-b969-95c9d9a19785"
        ],
        "failures": [],
        "pending": [],
        "skipped": [],
        "duration": 6757,
        "root": false,
        "rootEmpty": false,
        "_timeout": 2000
      }
    ],
    "passes": [],
    "failures": [],
    "pending": [],
    "skipped": [],
    "duration": 0,
    "root": true,
    "rootEmpty": true,
    "_timeout": 2000
  },
  "copyrightYear": 2019
}
```
when running `npx mochawesome-merge --reportDir cypress/reports/mocha > mochareports/report.json`

The following json file gets generated (mochareports/report.json):
```
{
  "stats": {
    "suites": 0,
    "tests": 0,
    "passes": 0,
    "pending": 0,
    "failures": 0,
    "start": "2019-06-05T12:55:09.464Z",
    "end": "2019-06-05T12:55:09.464Z",
    "duration": 0,
    "testsRegistered": 0,
    "passPercent": null,
    "pendingPercent": null,
    "other": 0,
    "hasOther": false,
    "skipped": 0,
    "hasSkipped": false,
    "passPercentClass": "warning",
    "pendingPercentClass": "danger"
  },
  "suites": {
    "uuid": "9c148315-0d70-4b5a-8e03-a893f8daafb9",
    "tests": [],
    "suites": [],
    "duration": 0,
    "root": true,
    "rootEmpty": true,
    "title": "",
    "fullFile": "",
    "file": "",
    "beforeHooks": [],
    "afterHooks": [],
    "passes": [],
    "failures": [],
    "pending": [],
    "skipped": [],
    "_timeout": 2000
  },
  "copyrightYear": 2019
}
```
finaly, when I run `npx marge mochareports/report.json -f report -o mochareports` I get the following error:
<img width="517" alt="Screenshot 2019-06-05 at 15 08 09" src="https://user-images.githubusercontent.com/27348820/58958713-cff6fc80-87a3-11e9-84a0-cf698064eda5.png">

**Comment by Antontelesh** [comment] 2019-06-05 14:41
`mochawesome-merge` is incompatible with `mochawesome@4`. Please, downgrade your mochawesome to version 3.

Closing this as a duplicate of #12

**Closed by Antontelesh** 2019-06-05 14:41 UTC

**Comment by deane187** [comment] 2019-06-05 15:24
Hi @Antontelesh This is still an issue, I downgraded mochawesome to version 3.

```
    "mocha": "5.2.0",
    "mochawesome": "^3.1.2",
    "mochawesome-merge": "^1.0.7",
    "mochawesome-report-generator": "^3.1.5"
```

**Comment by Antontelesh** [comment] 2019-06-05 15:46
@deane187 what are the filenames of your mochawesome reports?

**Comment by Kushagrawal** [comment] 2019-09-20 14:43
@deane187 I was facing the same issue while I was using the mochawesome-report-generator version - 4.0.0 but got resolve after switching to 3.1.5, this is my other libraries versions-
```    
    "mocha": "^6.1.4",
    "mochawesome": "^3.1.1",
    "mochawesome-merge": "^1.0.7",
    "mochawesome-report-generator": "^3.1.5",
```

**Comment by arinanda** [comment] 2020-01-06 05:29
Hi @Antontelesh @Kushagrawal , I recently facing the same issue with v3
```
    "mochawesome": "^3.1.2",
    "mochawesome-merge": "^1.0.7",
    "mochawesome-report-generator": "^3.1.5",
```

could you please help?

**Comment by Antontelesh** [comment] 2020-01-06 07:08
@arinanda, please update to the latest version. v1 is not supported anymore

**Comment by arinanda** [comment] 2020-01-07 08:10
> @arinanda, please update to the latest version. v1 is not supported anymore

@Antontelesh thanks for your quick response, I've updated it to newer version and the issue is no longer exist, thanks 👍🏻

**Comment by vanquy72dn** [comment] 2020-01-30 08:15
@arinanda Please help me show the version in details. Thanks

**Comment by ericrommel** [comment] 2023-12-05 14:22
Hey folks, long time after this error but I have gotten exactly the same error (happing only from my Bamboo CI):

> 05-Dec-2023 07:17:47 | ✘ Some files could not be processed:
05-Dec-2023 07:17:47 | reports/tests/mochawsome-bundle.json
05-Dec-2023 07:17:47 | Invalid value null supplied to /stats/passPercent: Number
05-Dec-2023 07:17:47 | Invalid value null supplied to /stats/pendingPercent: Number

Versions in use:
> "mocha": "^10.2.0"
"mochawesome": "^7.1.3"
"mochawesome-merge": "^4.3.0"
"cypress": "12.17.2",


and as per dependency for mochawesome:
>"mochawesome-report-generator": "^6.2.0"
