### ISSUE TITLE
✘ Some files could not be processed: report.json

### ISSUE THREAD

**Issue by Manuel-Suarez-Abascal** [Antontelesh/mochawesome-merge#88] opened 2022-12-02 20:51 UTC
After merging the reports & launching the HTML report successfully, I get the error: `✘ Some files could not be processed:
report.json`. How can I fix this issue? I tried downgrading to version `3.0.0`, but it didn't solve this issue.

My `package.json` file:

```json
...
"scripts": {
  ...
  "clean:reports": "rm -R -f cypress/reports && mkdir cypress/reports && mkdir cypress/reports/mochareports",
  "pretest": "npm run clean:reports",
  "scripts": "cypress run",
  "combine-reports": "mochawesome-merge cypress/reports/mocha/*.json > cypress/reports/mochareports/report.json",
  "generate-report": "marge cypress/reports/mochareports/ report.json -f report -o cypress/reports/mochareports",
  "posttest": "npm run combine-reports && npm run generate-report",
  "test": "npm run scripts || npm run posttest"
},
"devDependencies": {
  ...
  "cypress": "9.7.0",
  ...
  "cypress-multi-reporters": "^1.6.1",
  "eslint": "^8.15.0",
  "eslint-plugin-cypress": "^2.12.1",
  "husky": "^8.0.1",
  "lint-staged": "^12.4.1",
  "mocha": "^10.0.0",
  "mochawesome": "^7.1.3",
  "mochawesome-merge": "^4.2.1",
  "mochawesome-report-generator": "^6.2.0",
  ...
},
...
```

My `cypress.json` file:

```json
...
"reporter": "cypress-multi-reporters",
  "reporterOptions": {
    "reporterEnabled": "mochawesome",
    "mochawesomeReporterOptions": {
      "reportDir": "cypress/reports/mocha",
      "quite": true,
      "overwrite": false,
      "html": false,
      "json": true
    }
  },
  ...
```

I have added a screenshot for better context:

<img width="1282" alt="Screenshot 2022-12-02 at 3 45 09 PM" src="https://user-images.githubusercontent.com/32891808/205383875-42fd8a4e-ce5a-45b2-9e06-74bc6b4e4f5a.png">

**NodeJS:** `v19.1.0`.
**OS**:  13.0 (22A380) (MacBook Pro 13-inch, M1, 2020)

**Comment by Antontelesh** [comment] 2022-12-02 21:57
Hi @Manuel-Suarez-Abascal. Please, check the `report.json` after merging. Does it look as a valid JSON?

Can you also compare the structure of your merged report to that from one of the source reports used for merging? I haven’t found any recent changes in mochawesome report structure, but still makes sense to verify the structure is still compatible

**Comment by Manuel-Suarez-Abascal** [comment] 2022-12-02 22:13
Hi @Antontelesh thanks for your fast reply. I copied & pasted the entire content of the generated `json` file [here](https://jsonformatter.curiousconcept.com/#) & it came successfully validated as a valid`json` file.

<img width="1348" alt="Screenshot 2022-12-02 at 5 12 00 PM" src="https://user-images.githubusercontent.com/32891808/205399025-57e39ee1-d876-458f-9da0-8cf73a792dc1.png">

**Comment by Antontelesh** [comment] 2022-12-02 23:38
Did you compare it to original files? I wonder if original files contain some new properties that are not copied during merge

**Comment by Manuel-Suarez-Abascal** [comment] 2022-12-04 22:29
@Antontelesh it seems they both have the same properties, except in the `test` property which is an `array` containing the `it` blocks per file. Do you think this is what's causing the issue? I have added a screenshot below for better context:

<img width="1431" alt="Screenshot 2022-12-04 at 5 27 05 PM" src="https://user-images.githubusercontent.com/32891808/205519247-efbdad5e-e26d-45da-9245-080212f5d7d6.png">

**Comment by Antontelesh** [comment] 2022-12-04 22:56
@Manuel-Suarez-Abascal I didn’t get, what’s the difference in `tests`?

Also, can you try supplying one of the source reports to `marge` and verify the problem does not exist there? I'd like to verify the root cause is in `mochawesome-merge`

**Closed** 2022-12-12 01:05 UTC
