### ISSUE TITLE
Cannot read property 'meta' of undefined when merge is run

### ISSUE THREAD

**Issue by deane187** [Antontelesh/mochawesome-merge#15] opened 2019-06-05 17:24 UTC
Hi Guys @Antontelesh, @YOU54F

Awesome work and great response time!

`npx mochawesome-merge --reportDir cypress/reports/mocha > mochareports/report.json`
I get the following error when i try to merge:
```
ERROR: Failed to merge reports

TypeError: Cannot read property 'meta' of undefined
    at merge (/Users/deane.rousseau/Developer/automated-tests/node_modules/mochawesome-merge/lib/index.js:59:22)
deane-rousseau% npx mochawesome-merge --reportDir cypress/reports/mocha > mochareports/report.json
ERROR: Failed to merge reports

TypeError: Cannot read property 'meta' of undefined
    at merge (/Users/deane.rousseau/Developer/automated-tests/node_modules/mochawesome-merge/lib/index.js:59:22)
```
These are my dependencies:
```
"devDependencies": {
    "crypto": "^1.0.1",
    "cypress": "^3.3.1",
    "cypress-dark": "^1.7.13",
    "cypress-multi-reporters": "^1.1.20",
    "cypress-slack-reporter": "^0.3.1",
    "cypress-xpath": "^1.4.0",
    "dotenv-safe": "^6.1.0",
    "mocha": "^6.1.4",
    "mocha-junit-reporter": "^1.21.0",
    "mocha-junit-reporters": "^1.23.6",
    "mocha-multi-reporters": "^1.1.7",
    "mocha-slack-reporter": "0.0.8",
    "mochawesome": "^4.0.0",
    "mochawesome-merge": "^2.0.0",
    "mochawesome-report-generator": "^4.0.0",
    "moment": "^2.24.0",
    "twit": "^2.2.11",
    "twitter": "^1.7.1",
    "util.promisify": "^1.0.0"
  }
```
Theres also a warning: `npm WARN cypress-slack-reporter@0.3.1 requires a peer of mochawesome@^3.1.1 but none is installed. You must install peer dependencies yourself.`

_Originally posted by @deane187 in https://github.com/Antontelesh/mochawesome-merge/issues/12#issuecomment-499175522_

**Comment by Antontelesh** [comment] 2019-06-05 19:25
Thank you for opening this, @deane187.

This error can happen only if there are no reports to merge are found. While I will be glad to improve the error handling for this particular case, this error reveals another problem that you faced - no reports were found. So please, check that you have `mochawesomeXXX.json` files in your directory (where XXX is the numeric value).

**Comment by YOU54F** [comment] 2019-06-05 19:36
I think this also relates to #10 

It would be nice to be able to have configurable report names ( it’s useful for me for my cypress-circleci package, as I create a seperate report for each parallel run and then merge them later)

I’ve got an idea of how we can support it, so will propose a change soon, but as @Antontelesh states, as long as it follows the mochawesomexxx.json format, you should be ok.

I’ll sort out the peer deps issue in cypress-slack-reporter and push up a new version shortly :)

**Comment by Antontelesh** [comment] 2019-06-05 19:39
Makes sense to close this issue and continue discussion under #10. You agree, @deane187?

Thank you, @YOU54F

**Comment by deane187** [comment] 2019-06-05 19:41
Thank you, I agree @Antontelesh . I'm checking my config now. I have json files in the folder. going through it step by step. ok to close.

**Comment by Antontelesh** [comment] 2019-06-05 19:51
If your files exist but `mochawesome-merge` cannot find them, there might be another issue. Could you try debugging yourself? Check that [`reports`](https://github.com/Antontelesh/mochawesome-merge/blob/95f272b3d1e9cb8aecf3c2f3b06793deeca25b6c/lib/index.js#L54) variable contains your reports.

I won’t close this issue until I get confirmation from you that you face the issue described in #10

**Comment by deane187** [comment] 2019-06-05 20:48
Got it working!!! so this time around I did not give the json files a unique name, I let mochawesome specify it `mochawesomeXXX.json`. 

When executing `npx mochawesome-merge --reportDir cypress/reports/mocha > mochareports/report.json` , The merged json file is created. 

I was able to execute `npx marge mochareports/report.json -f report -o mochareports` and then finally report to slack.

**Comment by Antontelesh** [comment] 2019-06-05 21:03
So, this was a duplicate of #10.
Ok, I’m closing this. Thank you

**Closed by Antontelesh** 2019-06-05 21:03 UTC

**Comment by deane187** [comment] 2019-06-05 21:08
Thanks again @Antontelesh appreciate all the help and speedy response.

**Comment by ANanadikar** [comment] 2020-02-19 08:52
my tests are running successfully in local machine however on gitlab i am getting this issue.
Any suggestions please.

my dependencies are.

    "cypress": "^3.4.1",
    "cypress-multi-reporters": "^1.2.4",
    "cypress-plugin-retries": "^1.5.2",
    "cypress-plugin-tab": "^1.0.5",
    "cypress-select-tests": "^1.5.0",
    "cypress-visual-regression": "^1.0.5",
    "cypress-xpath": "^1.4.0",
    "mocha": "^5.2.0",
    "mochawesome": "^4.1.0",
    "mochawesome-merge": "^2.1.0",
    "mochawesome-report-generator": "^4.1.0"

![image](https://user-images.githubusercontent.com/36496598/74817587-6e5ccb00-52fd-11ea-8558-5c55d09a78f1.png)

**Comment by Antontelesh** [comment] 2020-02-19 12:17
@ANanadikar version 2 is no longer supported. Consider updating to the latest

**Comment by ANanadikar** [comment] 2020-03-02 08:31
@Antontelesh - Hi i tried to change the version of mochawesome merge to latest however no luck.error is different now.Just to highlight that the old mochawesome merge version is working fine on local machine however with gitlab i am getting this issue.

(please look at the red marked square wherein out of 11 specs only one has executed and for rest specs it didn't run)

below is my dependencies.Request you to please help me out in this..

![image](https://user-images.githubusercontent.com/36496598/75657865-2343a000-5c8d-11ea-9bbc-5ce4312c65a7.png)



![image](https://user-images.githubusercontent.com/36496598/75657844-1757de00-5c8d-11ea-98d4-b8c4ebe877e0.png)

**Comment by ANanadikar** [comment] 2020-03-02 08:34
> @ANanadikar version 2 is no longer supported. Consider updating to the latest

@Antontelesh - Hi i tried to change the version of mochawesome merge to latest however no luck.error is different now.Just to highlight that the old mochawesome merge version is working fine on local machine however with gitlab i am getting this issue.

(please look at the red marked square wherein out of 11 specs only one has executed and for rest specs it didn't run)

below is my dependencies.Request you to please help me out in this..

![image](https://user-images.githubusercontent.com/36496598/75657865-2343a000-5c8d-11ea-9bbc-5ce4312c65a7.png)



![image](https://user-images.githubusercontent.com/36496598/75657844-1757de00-5c8d-11ea-98d4-b8c4ebe877e0.png)

**Comment by Antontelesh** [comment] 2020-03-02 19:07
@ANanadikar I don’t know how do you use mochawesome-merge. Please, make sure you are following the API from readme.md

**Comment by Antontelesh** [comment] 2020-03-02 21:11
@ANanadikar I have created the [migration guide to v4](https://github.com/Antontelesh/mochawesome-merge#migration-to-v4). Hope it helps
