### ISSUE TITLE
"Unexpected end of JSON input" while doing mochawesome-merge

### ISSUE THREAD

**Issue by RajS999** [Antontelesh/mochawesome-merge#73] opened 2021-09-21 14:21 UTC
I tried removing spaces in command as suggested in [this](https://github.com/cypress-io/cypress/issues/5103#issuecomment-555366159) post. I also tried to reencode mochawesome.json as suggested in [this](https://github.com/Antontelesh/mochawesome-merge/issues/6#issuecomment-627496076) post. But non worked. 

You can find my json files [here](https://drive.google.com/drive/folders/1ov47UI3q6zHLypncPjI30czj8nw9HPPb?usp=sharing) on gdrive. (Github wasnt allowing to upload json)

When I try to merge them, I get following error:

```
npx mochawesome-merge cypress/reports/test/test/*.json>cypress/reports/test/test/merged_report.json 
Debugger attached.
Debugger attached.
ERROR: Failed to merge reports

SyntaxError: cypress/reports/test/test/merged_report.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at F:\myproj-testing\node_modules\mochawesome-merge\node_modules\jsonfile\index.js:33:18
    at F:\myproj-testing\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...

```

I am on Windows 10.
Here is my version information:

```
  "dependencies": {
    "cypress": "^8.3.0",
    "cypress-file-upload": "^5.0.8"
  },
  "devDependencies": {
    "mocha": "^9.1.1",
    "mochawesome": "^6.2.2",
    "mochawesome-merge": "^4.2.0"
  }
```

And node related version:

```
>node --version
v14.16.0

> npm --version
Debugger attached.
6.14.11
```

**Comment by Antontelesh** [comment] 2021-09-21 17:31
Let’s wait for some Windows command line experts to help. I don’t know how pipes on Windows work.

In the meantime I suggest you to switch to the JavaScript API. Write a simple script that utilizes the `merge` function and run it with node.

**Comment by RajS999** [comment] 2021-09-21 18:13
I didnt get "pipes on Windows". Why they are required here?
From the error "Unexpected end of JSON input", I guess its simply failing to parse one of the json files. Isnt it?

**Comment by Antontelesh** [comment] 2021-09-21 20:10
The `>` symbol in your command is a pipe signaling that it should output to the writable stream of your target file. But I don’t use Windows, and don’t know if these unix pipes work there the same way.

**Comment by Antontelesh** [comment] 2021-09-21 20:17
Checked your logs once again. It shouldn’t be related to the streams. Can you try logging the resolved input files produced by `glob` after parsing your input pattern?

**Comment by RajS999** [comment] 2021-09-21 20:26
Didnt get "Can you try logging the resolved input files produced by glob after parsing your input pattern?"...

I tried running just `mochawesome-merge cypress/reports/*.json` and it prints the merged json on the console. So I tried to first pipe merged json string to `.txt` file, then renaming `.txt` file to `.json` file and finally doing `marge`. Strangely it started working...

So these are my updated `package.json` scripts:

      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1",
        "merge":"mochawesome-merge cypress/reports/*.json>cypress/reports/merged_report.json",
        "mergetotxt":"mochawesome-merge cypress/reports/*.json > cypress/reports/merged_report.txt",
    
        "generate_mochawesome_report": "marge cypress/reports/merged_report.json --reportDir ./ --inline",
    
        "final_report": "npm run merge && npm run generate_mochawesome_report",
        "final_report2": "npm run mergetotxt && rename cypress\\reports\\merged_report.txt merged_report.json && npm run generate_mochawesome_report",
    
        "generate_report": "python cypress/utils/merge.py && npm run generate_mochawesome_report"
      }

Notice following two new scripts:

    "mergetotxt":"mochawesome-merge cypress/reports/*.json > cypress/reports/merged_report.txt",
    "final_report2": "npm run mergetotxt && rename cypress\\reports\\merged_report.txt merged_report.json && npm run generate_mochawesome_report",


Running `npm run final_report2` generates the desired report.

**Comment by Antontelesh** [comment] 2021-09-21 23:26
So, if it works without piping to the output than I would assume the issue is not with `mochawesome-merge`.

in this case I would recommend you to try using the `-o merged-report.json` flag to specify output file. It may simplify your setup

**Comment by jebril-ny-it** [comment] 2021-11-29 07:34
"merge":"mochawesome-merge cypress/reports/*.json>cypress/reports/output.json",
    "generate_mochawesome_report": "marge cypress/reports/output.json --reportDir ./ --inline",
    "final_report": "npm run merge && npm run generate_mochawesome_report"

I removed the spacing within (<) symbol. It worked for me.

**Comment by Antontelesh** [comment] 2021-12-02 19:03
Closing as it's confirmed to be unrelated to the package itself

**Closed by Antontelesh** 2021-12-02 19:03 UTC
